apiVersion: v1
kind: Service
metadata:
  name: travel-site-service
spec:
  type: NodePort
  selector:
    app: travel-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30090
